messages:
  # Сообщение если у игрока нет прав на команду
  no-access-message: "&7[&#DB4444✘&7] &7У вас &#DB4444нет прав &7на выполнение этой команды!"
  # Список доступных команд
  usage-commands-message:
    - "&6Команды:"
    - "&f"
    - "&6/vcustomeggs give [игрок] [яичко] [количество] &7- команда что бы выдать яичко"
    - "&6/vcustomeggs reload &7- команда что бы перезагрузить плагин"
    - "&f"
  # Сообщение если указанный игрок не найден
  no-player-message: "&7[&#DB4444✘&7] &7Игрок &#DB4444✘не &7найден!"
  # Сообщение когда яйцо выдано игроку
  egg-given-message: "&7[&#32CD32✔&7] &7Яйцо &#32CD32выдано &7игроку &6{player}!"
  # Сообщение если указано несуществующее яйцо
  bad-egg-message: "&7[&#DB4444✘&7] &7Такого яйца &#DB4444✘не &7существует!"
  # Сообщение когда плагин перезагружен
  reload-message: "&7[&#32CD32✔&7] &7Конфигурация &#32CD32успешно &7перезагружена!"
  # Сообщение если указано количество 0
  low-amount-message: "&7[&#DB4444✘&7] &7Количество должно быть больше &60&7!"
  # Сообщение если указано количество больше 64
  limit-message: "&7[&#DB4444✘&7] &#DB4444Нельзя &7выдать больше &664 &7предметов!"
  # Сообщение если указано некорректное количество (например не число)
  bad-amount-message: "&7[&#DB4444✘&7] &7Укажите &#32CD32правильное &7количество!"

#---------------------------------------------------------------------------------------

eggs:
  zombie_egg: # Айди яйца
    material: ZOMBIE_SPAWN_EGG # материал (ТОЛЬКО ЯЙЦА)
    name: "&#B481FFКастомное Яйцо" # название
    lore: # описание
      - ""
      - "&fУникальность:"
      - " &7содержит случайного"
      - " &7моба из списка"
      - ""
      - "  &7Зомби &7- &650%"
      - "  &7Зомби-житель &7- &630%"
      - "  &7Крипер &7- &620%"
      - "  &7Утопленик &7- &610%"
      - ""
    mobs: # шансы на мобов, если у 1 моба шанс 100, то спавниться будет он (2 моба с 100% сделать нельзя)
      - "ZOMBIE;50"
      - "ZOMBIE_VILLAGER;30"
      - "CREEPER;20"
      - "DROWNED;10"
    enchanted: true # будет ли яйцо зачарованое
    hide_attributes: true # скрывать атрибуты

  mixed_egg:
    material: CREEPER_SPAWN_EGG
    name: "&#F4E898Смешанное Яйцо"
    lore:
      - ""
      - "&fУникальность:"
      - " &7содержит случайного"
      - " &7моба из списка"
      - ""
      - "  &7Зомби &7- &640%"
      - "  &7Скилет &7- &630%"
      - "  &7Крипер &7- &620%"
      - "  &7Визер скелет &7- &610%"
      - ""
    mobs:
      - "ZOMBIE;40"
      - "SKELETON;30"
      - "CREEPER;20"
      - "WITHER_SKELETON;10"
    enchanted: false
    hide_attributes: false

  test:
    material: GHAST_SPAWN_EGG
    name: "&#F4E898Яйцо призыва Железного-голема"
    lore:
      - ""
      - "&fУникальность:"
      - " &7содержит в себе"
      - " &7железного голема!"
      - ""
      - "  &7Железный голем &7- &6100%"
      - ""
    mobs:
      - "IRON_GOLEM;100"
    enchanted: false
    hide_attributes: false
# ЧТО БЫ СОЗДАТЬ НОВОЕ ЯЙЦО ПРОСТО СКОПИРУЙТЕ ЗАГОТОВЛЕННЫЕ, ДАЙТЕ НОВОЕ АЙДИ И ВСЕ НАСТРОЙТЕ ПОД СЕБЯ